name: grpcassign
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-141.0.dev <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2+1
  flutter_next: ^0.1.0
  grpc: ^3.0.2
  http: ^0.13.4
  protobuf: ^2.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  import_sorter:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
